-- MySQL Script generated by MySQL Workbench
-- Tue Sep 20 11:04:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema regina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema regina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `regina` DEFAULT CHARACTER SET utf8 ;
USE `regina` ;

-- -----------------------------------------------------
-- Table `regina`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regina`.`estudiante` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(15) NOT NULL,
  `ap_paterno` VARCHAR(10) NOT NULL,
  `ap_materno` VARCHAR(10) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `lugar_nacimiento` VARCHAR(30) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `ci` VARCHAR(13) NOT NULL,
  `domicilio` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(12) NULL,
  `celular` VARCHAR(12) NULL,
  `email` VARCHAR(50) NOT NULL,
  `estado_civil` VARCHAR(10) NOT NULL,
  `ocupacion_actual` VARCHAR(50) NOT NULL,
  `idioma` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regina`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regina`.`materia` (
  `id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `paralelo` VARCHAR(45) NOT NULL,
  `siguiente` INT NOT NULL,
  `anterior` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regina`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regina`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `ap paterno` VARCHAR(16) NOT NULL,
  `ap materno` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regina`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regina`.`instructor` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `ap_materno` VARCHAR(45) NOT NULL,
  `ap_paterno` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regina`.`registro_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regina`.`registro_materia` (
  `id` INT NOT NULL,
  `estudiante_id` INT NOT NULL,
  `materia_materiacol` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `nota` DOUBLE NOT NULL,
  `costo` DOUBLE NOT NULL,
  `usuario_id` INT NOT NULL,
  `instructor_id` INT NOT NULL,
  INDEX `fk_estudiante_has_materia_materia1_idx` (`materia_materiacol` ASC) VISIBLE,
  INDEX `fk_estudiante_has_materia_estudiante_idx` (`estudiante_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_registro_materia_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_registro_materia_instructor1_idx` (`instructor_id` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_has_materia_estudiante`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `regina`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_has_materia_materia1`
    FOREIGN KEY (`materia_materiacol`)
    REFERENCES `regina`.`materia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_materia_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `regina`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_materia_instructor1`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `regina`.`instructor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regina`.`trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regina`.`trabajo` (
  `id` INT NOT NULL,
  `cargo` VARCHAR(50) NOT NULL,
  `institucion` VARCHAR(40) NOT NULL,
  `responsabilidades` VARCHAR(100) NOT NULL,
  `duracion` VARCHAR(50) NOT NULL,
  `estudiante_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trabajo_estudiante1_idx` (`estudiante_id` ASC) VISIBLE,
  CONSTRAINT `fk_trabajo_estudiante1`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `regina`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regina`.`cursos_seminarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regina`.`cursos_seminarios` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `certificacion` VARCHAR(255) NOT NULL,
  `duarion` VARCHAR(20) NOT NULL,
  `estudiante_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cursos_seminarios_estudiante1_idx` (`estudiante_id` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_seminarios_estudiante1`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `regina`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regina`.`formacion_academica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regina`.`formacion_academica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(25) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `desde` DATE NOT NULL,
  `hasta` DATE NOT NULL,
  `estudiante_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_formacion_academica_estudiante1_idx` (`estudiante_id` ASC) VISIBLE,
  CONSTRAINT `fk_formacion_academica_estudiante1`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `regina`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regina`.`respaldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regina`.`respaldo` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `imagen` BLOB(256) NOT NULL,
  `trabajo_id` INT NULL DEFAULT 0,
  `cursos_seminarios_id` INT NULL DEFAULT 0,
  `formacion_academica_id` INT NULL DEFAULT 0,
  INDEX `fk_respaldo_trabajo1_idx` (`trabajo_id` ASC) VISIBLE,
  INDEX `fk_respaldo_cursos_seminarios1_idx` (`cursos_seminarios_id` ASC) VISIBLE,
  INDEX `fk_respaldo_formacion_academica1_idx` (`formacion_academica_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_respaldo_trabajo1`
    FOREIGN KEY (`trabajo_id`)
    REFERENCES `regina`.`trabajo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respaldo_cursos_seminarios1`
    FOREIGN KEY (`cursos_seminarios_id`)
    REFERENCES `regina`.`cursos_seminarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respaldo_formacion_academica1`
    FOREIGN KEY (`formacion_academica_id`)
    REFERENCES `regina`.`formacion_academica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regina`.`cobro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regina`.`cobro` (
  `estudiante_id` INT NOT NULL,
  `registro_materia_id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `monto` DOUBLE NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `detalle` VARCHAR(255) NOT NULL,
  INDEX `fk_cobro_estudiante1_idx` (`estudiante_id` ASC) VISIBLE,
  INDEX `fk_cobro_registro_materia1_idx` (`registro_materia_id` ASC) VISIBLE,
  CONSTRAINT `fk_cobro_estudiante1`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `regina`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cobro_registro_materia1`
    FOREIGN KEY (`registro_materia_id`)
    REFERENCES `regina`.`registro_materia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `regina`.`referencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `regina`.`referencias` (
  `nombre` VARCHAR(40) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(12) NULL,
  `estudiante_id` INT NOT NULL,
  CONSTRAINT `fk_referencias_estudiante1`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `regina`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
